name: Build Weni WebApp (Connect) in Shared (Dispatch)

on:
  workflow_dispatch:
    inputs:

      source-branch:
        description: 'Source branch in Weni WebApp repository (main, staging, develop, fix/sentry etc.)'
        required: true
        default: 'main'

      tag-name:
        description: 'Tag id (v0.0.1-develop, v0.0.2, etc.)'
        required: true

      destination-env:
        description: 'Destination environment (develop, production, staging)'
        required: true

      vue_app_root_api:
        description: 'vue_app_root_api'
        required: true

      vue_app_hotjar_project_key:
        description: 'vue_app_hotjar_project_key'
        required: true

      vue_app_sentry_dsn_endpoint:
        description: 'vue_app_sentry_dsn_endpoint'
        required: true

      keycloak_issuer:
        description: 'keycloak_issuer'
        required: true

      keycloak_authorization_endpoint:
        description: 'keycloak_authorization_endpoint'
        required: true

      keycloak_userinfo_endpoint:
        description: 'keycloak_userinfo_endpoint'
        required: true

      keycloak_end_session_endpoint:
        description: 'keycloak_end_session_endpoint'
        required: true

      keycloak_jwks_uri:
        description: 'keycloak_jwks_uri'
        required: true

      keycloak_token_endpoint:
        description: 'keycloak_token_endpoint'
        required: true

      keycloak_check_session_iframe:
        description: 'keycloak_check_session_iframe'
        required: true

      keycloak_client_id:
        description: 'keycloak_client_id'
        required: true

      vue_app_helphero:
        description: 'vue_app_helphero'
        required: true

      logrocket_id:
        description: 'logrocket_id'
        required: true

      logrocket_child_domains:
        description: 'logrocket_child_domains'
        required: true

      vue_app_stripe_api:
        description: 'vue_app_stripe_api'
        required: true

      keycloak_realm:
        description: 'keycloak_realm'
        required: true

      VUE_APP_USERGUIDING_USER:
        description: 'VUE_APP_USERGUIDING_USER'
        required: true

      VUE_APP_USERGUIDING_WELCOME:
        description: 'VUE_APP_USERGUIDING_WELCOME'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.inputs.source-branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Login to ECR
      #   uses: docker/login-action@v1
      #   with:
      #     registry: 869898323958.dkr.ecr.us-east-1.amazonaws.com
      #     username: ${{ secrets.AWS_ACCESS_KEY_ID_SHARED }}
      #     password: ${{ secrets.AWS_SECRET_ACCESS_KEY_SHARED }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push - Weni WebApp Image
        id: docker_build1
        uses: docker/build-push-action@v2
        with:
          context: .
          labels: branch=${{github.event.inputs.source-branch}},commit=${{env.GITHUB_SHA}},repository=https://github.com/Ilhasoft/weni-webapp
          file: Dockerfile
          push: true
          tags: connectof/weni-webapp:${{github.event.inputs.tag-name}}
          no-cache: true
          build-args: |
            VUE_APP_HOTJAR_PROJECT_KEY=${{env.vue_app_hotjar_project_key}}
            VUE_APP_SENTRY_DSN_ENDPOINT=${{env.vue_app_sentry_dsn_endpoint}}
            KEYCLOAK_ISSUER=${{env.keycloak_issuer}}
            KEYCLOAK_AUTHORIZATION_ENDPOINT=${{env.keycloak_authorization_endpoint}}
            KEYCLOAK_USERINFO_ENDPOINT=${{env.keycloak_userinfo_endpoint}}
            KEYCLOAK_END_SESSION_ENDPOINT=${{env.keycloak_end_session_endpoint}}
            KEYCLOAK_JWKS_URI=${{env.keycloak_jwks_uri}}
            KEYCLOAK_TOKEN_ENDPOINT=${{env.keycloak_token_endpoint}}
            KEYCLOAK_CHECK_SESSION_IFRAME=${{env.keycloak_check_session_iframe}}
            KEYCLOAK_CLIENT_ID=${{env.keycloak_client_id}}
            VUE_APP_HELPHERO=${{env.vue_app_helphero}}
            LOGROCKET_ID=${{env.logrocket_id}}
            KEYCLOAK_REALM=${{env.keycloak_realm}}
            VUE_APP_USERGUIDING_USER=${{env.VUE_APP_USERGUIDING_USER}}
            VUE_APP_USERGUIDING_WELCOME=${{env.VUE_APP_USERGUIDING_WELCOME}}
            VUE_APP_STRIPE_API=${{env.vue_app_stripe_api}}
            LOGROCKET_CHILD_DOMAINS=${{env.logrocket_child_domains}}
            VUE_APP_URL_ACADEMY=${{env.vue_app_url_academy}}

      - name: Check out Kubernetes Manifests
        uses: actions/checkout@master
        with:
          ref: main
          repository: Ilhasoft/kubernetes-manifests-connect
          token: ${{ secrets.DEVOPS_GITHUB_PERMANENT_TOKEN }}
          path: ./kubernetes-manifests/

      - name: Set variable tag for jq
        run: |
          echo "IMAGE_TAG=connectof/weni-webapp:${{github.event.inputs.tag-name}}" >> $GITHUB_ENV

      - name: Update image on deployment
        run: |
            which jq > /dev/null 2>&1 || ( sudo apt update ; sudo apt install -y jq )
            # Dep: coreutils
            verlte() {
              [ "$1" = "`echo -e "$1\n$2" | sort -V | head -n1`" ]
            }
            verlt(){
              [ "$1" = "$2" ] && return 1 || verlte $1 $2
            }
            export PROJECT_DIR="connect-webapp" PATCH_TARGET="deployment.json"
            for e in ${{github.event.inputs.destination-env}}; do
              echo "Update ${e}:"
              if [ ! -d "kubernetes-manifests/${PROJECT_DIR}/${e}" ] ; then
                echo "kubernetes-manifests/${PROJECT_DIR}/${e}: Does not exist, skipping"
              elif [ ! -r "kubernetes-manifests/${PROJECT_DIR}/${e}/kustomization.yaml" ] ; then
                echo "kubernetes-manifests/${PROJECT_DIR}/${e}/kustomization.yaml: Does not readable, skipping"
              elif [ ! -r "kubernetes-manifests/${PROJECT_DIR}/${e}/${PATCH_TARGET}" ] ; then
                echo "kubernetes-manifests/${PROJECT_DIR}/${e}/${PATCH_TARGET}: Does not readable, skipping"
              else
                OLD_IMAGE=$(
                  cat "kubernetes-manifests/${PROJECT_DIR}/${e}/${PATCH_TARGET}" \
                    | jq '.[] | select(.path == "/spec/template/spec/containers/0/image") | .value'
                )
                echo "Old image to replace: ${OLD_IMAGE}"
                OLD_VERSION=$(
                  echo "${OLD_IMAGE}" \
                    | sed s'/^.*[v:-]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/'g \
                    | head -n1
                )
                NEW_VERSION=$(echo ${{github.event.inputs.tag-name}}|grep -o -e '[0-9]*\.[0-9]*\.[0-9]*')
                echo "Old image version to compare: ${OLD_VERSION}<=${NEW_VERSION}"
                if verlte "${OLD_VERSION}" "${NEW_VERSION}" ; then
                  echo 'New configurations:'
                  new_configuration=$(
                    cat "kubernetes-manifests/${PROJECT_DIR}/${e}/${PATCH_TARGET}" \
                      | jq '(..|select(.path == "/spec/template/spec/containers/0/image")?) += {value: "'"${{env.IMAGE_TAG}}"'"}'
                  )
                  echo "${new_configuration}"
                  echo "${new_configuration}" > "kubernetes-manifests/${PROJECT_DIR}/${e}/${PATCH_TARGET}"
                else
                  echo "Version in file is greater than build, skiping update yaml"
                fi
              fi
            done

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.DEVOPS_GITHUB_PERMANENT_TOKEN }}
          repository: Ilhasoft/kubernetes-manifests
          directory: ./kubernetes-manifests/
          branch: main
          message: "From Weni WebApp Build (Dispatch)"

      - name: Generated Image URL to Copy
        run: |
            echo ${{ env.IMAGE_TAG }}
