name: Build Weni Weni WebApp (Connect) in Shared (Push Tag)

on:
  push:
    tags:
      - 'v*.*.*-develop*'
      - 'v*.*.*-staging*'
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Set variables
        run: |
            TAG=$(echo $GITHUB_REF|cut -d"/" -f3)
            VUE_APP_ROOT_API=''  >> $GITHUB_ENV
            VUE_APP_HOTJAR_PROJECT_KEY='' >> $GITHUB_ENV
            VUE_APP_SENTRY_DSN_ENDPOINT='' >> $GITHUB_ENV
            KEYCLOAK_ISSUER='' >> $GITHUB_ENV
            KEYCLOAK_AUTHORIZATION_ENDPOINT='' >> $GITHUB_ENV
            KEYCLOAK_USERINFO_ENDPOINT='' >> $GITHUB_ENV
            KEYCLOAK_END_SESSION_ENDPOINT='' >> $GITHUB_ENV
            KEYCLOAK_JWKS_URI='' >> $GITHUB_ENV
            KEYCLOAK_TOKEN_ENDPOINT='' >> $GITHUB_ENV
            KEYCLOAK_CHECK_SESSION_IFRAME='' >> $GITHUB_ENV
            KEYCLOAK_CLIENT_ID='' >> $GITHUB_ENV
            VUE_APP_HELPHERO='' >> $GITHUB_ENV
            LOGROCKET_ID='' >> $GITHUB_ENV
            LOGROCKET_CHILD_DOMAINS='' >> $GITHUB_ENV
            VUE_APP_URL_ACADEMY='' >> $GITHUB_ENV
            if $(echo  $TAG|grep --silent -e 'v*.*.*-develop*')
            then
              echo "Found environment: DEVELOP - $TAG"
              echo "MANIFESTS_ENVIRONMENT=develop" >> $GITHUB_ENV
              echo "MANIFESTS_ENVIRONMENT=develop"
              echo "TAG=$TAG" >> $GITHUB_ENV
              echo "TAG=$TAG"
              VERSION=${TAG#v}
              echo "VERSION=$VERSION" >> $GITHUB_ENV
              echo "VERSION=$VERSION"
              echo "COMMIT_SHA=$GITHUB_SHA" >> $GITHUB_ENV
              echo "COMMIT_SHA=$GITHUB_SHA"
              echo "IMAGE_TAG=connectof/weni-webapp:$TAG" >> $GITHUB_ENV
              echo "IMAGE_TAG=connectof/weni-webapp:$TAG"
            elif $(echo  $TAG|grep --silent -e 'v*.*.*-staging*')
            then
              echo "Found environment: STAGING - $TAG"
              echo "MANIFESTS_ENVIRONMENT=staging" >> $GITHUB_ENV
              echo "MANIFESTS_ENVIRONMENT=staging"
              echo "TAG=$TAG" >> $GITHUB_ENV
              echo "TAG=$TAG"
              VERSION=${TAG#v}
              echo "VERSION=$VERSION" >> $GITHUB_ENV
              echo "VERSION=$VERSION"
              echo "COMMIT_SHA=$GITHUB_SHA" >> $GITHUB_ENV
              echo "COMMIT_SHA=$GITHUB_SHA"
              echo "IMAGE_TAG=connectof/weni-webapp:$TAG" >> $GITHUB_ENV
              echo "IMAGE_TAG=connectof/weni-webapp:$TAG"
            elif $(echo  $TAG|grep --silent -e 'v*.*.*')
            then
              echo "No environment found, assuming: PRODUCTION - $TAG"
              echo "MANIFESTS_ENVIRONMENT=production" >> $GITHUB_ENV
              echo "MANIFESTS_ENVIRONMENT=production"
              echo "TAG=$TAG" >> $GITHUB_ENV
              echo "TAG=$TAG"
              VERSION=${TAG#v}
              echo "VERSION=$VERSION" >> $GITHUB_ENV
              echo "VERSION=$VERSION"
              echo "COMMIT_SHA=$GITHUB_SHA" >> $GITHUB_ENV
              echo "COMMIT_SHA=$GITHUB_SHA"
              echo "IMAGE_TAG=connectof/weni-webapp:$TAG" >> $GITHUB_ENV
              echo "IMAGE_TAG=connectof/weni-webapp:$TAG"
            else
              echo 'Not a valid tag. Skipping...'
              exit 1
            fi

      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: ${{env.GITHUB_SHA}}
          repository: Ilhasoft/weni-webapp

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Login to ECR
      #   uses: docker/login-action@v1
      #   with:
      #     registry: 869898323958.dkr.ecr.us-east-1.amazonaws.com
      #     username: ${{secrets.AWS_ACCESS_KEY_ID_SHARED}}
      #     password: ${{secrets.AWS_SECRET_ACCESS_KEY_SHARED}}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push - Weni WebApp Image
        id: docker_build1
        uses: docker/build-push-action@v2
        with:
          context: .
          labels: branch=${{env.TAG}},commit=${{env.COMMIT_SHA}},repository=https://github.com/Ilhasoft/weni-webapp
          file: Dockerfile
          push: true
          tags: ${{env.IMAGE_TAG}}
          no-cache: true
          build-args: |
            VUE_APP_ROOT_API=${{env.VUE_APP_ROOT_API}}
            VUE_APP_HOTJAR_PROJECT_KEY=${{env.VUE_APP_HOTJAR_PROJECT_KEY}}
            VUE_APP_SENTRY_DSN_ENDPOINT=${{env.VUE_APP_SENTRY_DSN_ENDPOINT}}
            KEYCLOAK_ISSUER=${{env.KEYCLOAK_ISSUER}}
            KEYCLOAK_AUTHORIZATION_ENDPOINT=${{env.KEYCLOAK_AUTHORIZATION_ENDPOINT}}
            KEYCLOAK_USERINFO_ENDPOINT=${{env.KEYCLOAK_USERINFO_ENDPOINT}}
            KEYCLOAK_END_SESSION_ENDPOINT=${{env.KEYCLOAK_END_SESSION_ENDPOINT}}
            KEYCLOAK_JWKS_URI=${{env.KEYCLOAK_JWKS_URI}}
            KEYCLOAK_TOKEN_ENDPOINT=${{env.KEYCLOAK_TOKEN_ENDPOINT}}
            KEYCLOAK_CHECK_SESSION_IFRAME=${{env.KEYCLOAK_CHECK_SESSION_IFRAME}}
            KEYCLOAK_CLIENT_ID=${{env.KEYCLOAK_CLIENT_ID}}
            VUE_APP_HELPHERO=${{env.VUE_APP_HELPHERO}}
            LOGROCKET_ID=${{env.LOGROCKET_ID}}
            LOGROCKET_CHILD_DOMAINS=${{env.LOGROCKET_CHILD_DOMAINS}}
            VUE_APP_URL_ACADEMY=${{env.VUE_APP_URL_ACADEMY}}

      - name: Check out Kubernetes Manifests
        uses: actions/checkout@master
        with:
          ref: main
          repository: Ilhasoft/kubernetes-manifests-connect
          token: ${{secrets.DEVOPS_GITHUB_PERMANENT_TOKEN}}
          path: ./kubernetes-manifests/

      - name: Update image on deployment
        run: |
            which jq > /dev/null 2>&1 || ( sudo apt update ; sudo apt install -y jq )
            # Dep: coreutils
            verlte() {
              [ "$1" = "`echo -e "$1\n$2" | sort -V | head -n1`" ]
            }
            verlt(){
              [ "$1" = "$2" ] && return 1 || verlte $1 $2
            }
            export PROJECT_DIR="connect-webapp" PATCH_TARGET="deployment.json"
            for e in ${{env.MANIFESTS_ENVIRONMENT}}; do
              echo "Update ${e}:"
              if [ ! -d "kubernetes-manifests/${PROJECT_DIR}/${e}" ] ; then
                echo "kubernetes-manifests/${PROJECT_DIR}/${e}: Does not exist, skipping"
              elif [ ! -r "kubernetes-manifests/${PROJECT_DIR}/${e}/kustomization.yaml" ] ; then
                echo "kubernetes-manifests/${PROJECT_DIR}/${e}/kustomization.yaml: Does not readable, skipping"
              elif [ ! -r "kubernetes-manifests/${PROJECT_DIR}/${e}/${PATCH_TARGET}" ] ; then
                echo "kubernetes-manifests/${PROJECT_DIR}/${e}/${PATCH_TARGET}: Does not readable, skipping"
              else
                OLD_IMAGE=$(
                  cat "kubernetes-manifests/${PROJECT_DIR}/${e}/${PATCH_TARGET}" \
                    | jq '.[] | select(.path == "/spec/template/spec/containers/0/image") | .value'
                )
                echo "Old image to replace: ${OLD_IMAGE}"
                OLD_VERSION=$(
                  echo "${OLD_IMAGE}" \
                    | sed s'/^.*[v:-]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/'g \
                    | head -n1
                )
                echo "Old image version to compare: ${OLD_VERSION}<=${{env.VERSION}}"
                if verlte "${OLD_VERSION}" "${{env.VERSION}}" ; then
                  echo 'New configurations:'
                  new_configuration=$(
                    cat "kubernetes-manifests/${PROJECT_DIR}/${e}/${PATCH_TARGET}" \
                      | jq '(..|select(.path == "/spec/template/spec/containers/0/image")?) += {value: "'"${{env.IMAGE_TAG}}"'"}'
                  )
                  echo "${new_configuration}"
                  echo "${new_configuration}" > "kubernetes-manifests/${PROJECT_DIR}/${e}/${PATCH_TARGET}"
                else
                  echo "Version in file is greater than build, skiping update yaml"
                fi
              fi
            done

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.DEVOPS_GITHUB_PERMANENT_TOKEN }}
          repository: Ilhasoft/kubernetes-manifests-connect
          directory: ./kubernetes-manifests/
          branch: main
          message: "From Weni WebApp Build (Push-Tag)"

      - name: Generated Image
        run: |
            echo "IMAGE:      " ${{env.IMAGE_TAG}}
